#include <stdio.h>
#include <stdlib.h>
#include <math.h>

int main(int argc, char *argv[]) 
{ 
    int i=0;
    double sx;
    double sy;
    double zx;
    double zy;
    int rx;
    int ry;
    int nflag = 0;

    if (argc < 3) {
	fprintf(stderr,"usage: mk_scale x y\n");
	return 1;
    }

    for (i = 1; i < argc; i++){
	if (argv[i][0] == '-' ){
	    switch (argv[i][1]) {
	    case 'n':  /* don't make reverse translation */
		nflag = 1;
		break;
	    default:
		fprintf(stderr,"error: bad option.\n");
		exit(1);
	    }
	}
	else break;
    }

    sx = strtod(argv[i],NULL) / 512;
    sy = strtod(argv[i+1],NULL) / 512;
    rx = atoi(argv[i])-1;
    ry = atoi(argv[i+1])-1;
    zx = 512 / strtod(argv[i],NULL);
    zy = 512 / strtod(argv[i+1],NULL);
    
    printf(
	   "/* ! Autogenerated by tools/mk_scale.c */\n\n"
	   "#ifndef SCALE_H\n"
	   "#define SCALE_H\n\n"
	   "unsigned short scalex[]={\n");

    for (i=0;i<512;i++) { 
	printf("%d,",(int)floor(i*sx));
	if( i % 8 == 7 )
	    printf("\n");
    }
    printf("};\n\n");
    
    printf("unsigned short scaley[]={\n");
    for (i=511;i>=0;i-=1) {
	printf("%d,",(int)floor(i*sy));
	if (i % 8 == 0 )
	    printf("\n");
    } 
    printf("};\n\n");

    if (!nflag) {
	printf("unsigned short scaletx[]={\n");

	for (i=0;i<rx;i++) {
	    printf("%d,",(int)floor(i*zx));
	    if( i % 8 == 7 )
		printf("\n");
	}
	printf("};\n\n");

	printf("unsigned short scalety[]={\n");
	for (i=ry;i>=0;i-=1) {
	    printf("%d,",(int)floor(i*zy));
	    if (i % 8 == 0 )
		printf("\n");
	}
	printf("};\n\n");
    }
    printf("#endif  /* scale_h */\n");
    return 0;
}
